
package cz.cvut.fel.aos.service.reservation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Oct 24 21:34:41 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "SecurityFault", targetNamespace = "http://reservation.service.bookingserver.aos.fel.cvut.cz/")
public class SecurityException extends Exception {
    public static final long serialVersionUID = 20121024213441L;
    
    private cz.cvut.fel.aos.service.reservation.SecurityFault securityFault;

    public SecurityException() {
        super();
    }
    
    public SecurityException(String message) {
        super(message);
    }
    
    public SecurityException(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityException(String message, cz.cvut.fel.aos.service.reservation.SecurityFault securityFault) {
        super(message);
        this.securityFault = securityFault;
    }

    public SecurityException(String message, cz.cvut.fel.aos.service.reservation.SecurityFault securityFault, Throwable cause) {
        super(message, cause);
        this.securityFault = securityFault;
    }

    public cz.cvut.fel.aos.service.reservation.SecurityFault getFaultInfo() {
        return this.securityFault;
    }
}
