package cz.cvut.fel.aos.service.reservation;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sat Nov 03 16:20:17 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "FullFlightFault", targetNamespace = "http://reservation.service.aos.fel.cvut.cz/" )
public class FullFlightException extends Exception {

    public static final long serialVersionUID = 20121103162017L;

    private cz.cvut.fel.aos.service.reservation.FullFlightFault fullFlightFault;

    public FullFlightException() {
        super();
    }

    public FullFlightException( String message ) {
        super( message );
    }

    public FullFlightException( String message, Throwable cause ) {
        super( message, cause );
    }

    public FullFlightException( String message, cz.cvut.fel.aos.service.reservation.FullFlightFault fullFlightFault ) {
        super( message );
        this.fullFlightFault = fullFlightFault;
    }

    public FullFlightException( String message, cz.cvut.fel.aos.service.reservation.FullFlightFault fullFlightFault, Throwable cause ) {
        super( message, cause );
        this.fullFlightFault = fullFlightFault;
    }

    public cz.cvut.fel.aos.service.reservation.FullFlightFault getFaultInfo() {
        return this.fullFlightFault;
    }
}
