/*
*
*/

package cz.cvut.fel.aos.payment.service.payment;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/** This class was generated by Apache CXF 2.3.1 Sun Oct 28 21:23:36 CET 2012 Generated source version: 2.3.1 */


@WebServiceClient( name = "PaymentServiceImplService",
        wsdlLocation = "http://localhost:8080/PaymentServer/PaymentService?wsdl",
        targetNamespace = "http://payment.service.payment.aos.fel.cvut.cz/" )
public class PaymentServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName( "http://payment.service.payment.aos.fel.cvut.cz/", "PaymentServiceImplService" );

    public final static QName PaymentServiceImplPort = new QName( "http://payment.service.payment.aos.fel.cvut.cz/", "PaymentServiceImplPort" );

    static {
        URL url = null;
        try {
            url = new URL( "http://localhost:8080/PaymentServer/PaymentService?wsdl" );
        } catch ( MalformedURLException e ) {
            System.err.println( "Can not initialize the default wsdl from http://localhost:8080/PaymentServer/PaymentService?wsdl" );
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PaymentServiceImplService( URL wsdlLocation ) {
        super( wsdlLocation, SERVICE );
    }

    public PaymentServiceImplService( URL wsdlLocation, QName serviceName ) {
        super( wsdlLocation, serviceName );
    }

    public PaymentServiceImplService() {
        super( WSDL_LOCATION, SERVICE );
    }


    /** @return returns PaymentService */
    @WebEndpoint( name = "PaymentServiceImplPort" )
    public PaymentService getPaymentServiceImplPort() {
        return super.getPort( PaymentServiceImplPort, PaymentService.class );
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will
     *                 have their default values.
     *
     * @return returns PaymentService
     */
    @WebEndpoint( name = "PaymentServiceImplPort" )
    public PaymentService getPaymentServiceImplPort( WebServiceFeature... features ) {
        return super.getPort( PaymentServiceImplPort, PaymentService.class, features );
    }

}
