/*
*
*/

package cz.cvut.fel.aos.service.print;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/** This class was generated by Apache CXF 2.3.1 Sat Nov 03 16:18:42 CET 2012 Generated source version: 2.3.1 */


@WebServiceClient( name = "PrintServiceImplService",
        wsdlLocation = "http://localhost:8080/PrintService?wsdl",
        targetNamespace = "http://print.service.aos.fel.cvut.cz/" )
public class PrintServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName( "http://print.service.aos.fel.cvut.cz/", "PrintServiceImplService" );

    public final static QName PrintServiceImplPort = new QName( "http://print.service.aos.fel.cvut.cz/", "PrintServiceImplPort" );

    static {
        URL url = null;
        try {
            url = new URL( "http://localhost:8080/PrintService?wsdl" );
        } catch ( MalformedURLException e ) {
            System.err.println( "Can not initialize the default wsdl from http://localhost:8080/PrintService?wsdl" );
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PrintServiceImplService( URL wsdlLocation ) {
        super( wsdlLocation, SERVICE );
    }

    public PrintServiceImplService( URL wsdlLocation, QName serviceName ) {
        super( wsdlLocation, serviceName );
    }

    public PrintServiceImplService() {
        super( WSDL_LOCATION, SERVICE );
    }


    /** @return returns PrintService */
    @WebEndpoint( name = "PrintServiceImplPort" )
    public PrintService getPrintServiceImplPort() {
        return super.getPort( PrintServiceImplPort, PrintService.class );
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will
     *                 have their default values.
     *
     * @return returns PrintService
     */
    @WebEndpoint( name = "PrintServiceImplPort" )
    public PrintService getPrintServiceImplPort( WebServiceFeature... features ) {
        return super.getPort( PrintServiceImplPort, PrintService.class, features );
    }

}
