package cz.cvut.fel.aos.service.print;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by Apache CXF 2.3.1 Sat Nov 03 16:18:42 CET 2012 Generated source version: 2.3.1 */

@WebService( targetNamespace = "http://print.service.aos.fel.cvut.cz/", name = "PrintService" )
@XmlSeeAlso( { ObjectFactory.class } )
public interface PrintService {

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "printPaymentConfirmation", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintPaymentConfirmation" )
    @WebMethod
    @ResponseWrapper( localName = "printPaymentConfirmationResponse", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintPaymentConfirmationResponse" )
    public javax.activation.DataHandler printPaymentConfirmation(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "cardNumber", targetNamespace = "" )
            long cardNumber,
            @WebParam( name = "amount", targetNamespace = "" )
            int amount
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "printTicket", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintTicket" )
    @WebMethod
    @ResponseWrapper( localName = "printTicketResponse", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintTicketResponse" )
    public javax.activation.DataHandler printTicket(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password,
            @WebParam( name = "flightNumber", targetNamespace = "" )
            long flightNumber,
            @WebParam( name = "destinationFrom", targetNamespace = "" )
            java.lang.String destinationFrom,
            @WebParam( name = "destinationTo", targetNamespace = "" )
            java.lang.String destinationTo,
            @WebParam( name = "takeOff", targetNamespace = "" )
            java.util.Date takeOff
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "printReservationConfirmation", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintReservationConfirmation" )
    @WebMethod
    @ResponseWrapper( localName = "printReservationConfirmationResponse", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintReservationConfirmationResponse" )
    public javax.activation.DataHandler printReservationConfirmation(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password,
            @WebParam( name = "flightNumber", targetNamespace = "" )
            long flightNumber,
            @WebParam( name = "destinationFrom", targetNamespace = "" )
            java.lang.String destinationFrom,
            @WebParam( name = "destinationTo", targetNamespace = "" )
            java.lang.String destinationTo,
            @WebParam( name = "takeOff", targetNamespace = "" )
            java.util.Date takeOff,
            @WebParam( name = "cost", targetNamespace = "" )
            int cost
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "printCancelConfirmation", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintCancelConfirmation" )
    @WebMethod
    @ResponseWrapper( localName = "printCancelConfirmationResponse", targetNamespace = "http://print.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.print.PrintCancelConfirmationResponse" )
    public javax.activation.DataHandler printCancelConfirmation(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "flightNumber", targetNamespace = "" )
            long flightNumber,
            @WebParam( name = "destinationFrom", targetNamespace = "" )
            java.lang.String destinationFrom,
            @WebParam( name = "destinationTo", targetNamespace = "" )
            java.lang.String destinationTo,
            @WebParam( name = "takeOff", targetNamespace = "" )
            java.util.Date takeOff
    );
}
