/*
*
*/

package cz.cvut.fel.aos.service.facade;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */


@WebServiceClient( name = "FacadeServiceImplService",
        wsdlLocation = "http://localhost:8080/InterfaceServer/FacadeService?wsdl",
        targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class FacadeServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName( "http://facade.service.aos.fel.cvut.cz/", "FacadeServiceImplService" );

    public final static QName FacadeServiceImplPort = new QName( "http://facade.service.aos.fel.cvut.cz/", "FacadeServiceImplPort" );

    static {
        URL url = null;
        try {
            url = new URL( "http://localhost:8080/InterfaceServer/FacadeService?wsdl" );
        } catch ( MalformedURLException e ) {
            System.err.println( "Can not initialize the default wsdl from http://localhost:8080/InterfaceServer/FacadeService?wsdl" );
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FacadeServiceImplService( URL wsdlLocation ) {
        super( wsdlLocation, SERVICE );
    }

    public FacadeServiceImplService( URL wsdlLocation, QName serviceName ) {
        super( wsdlLocation, serviceName );
    }

    public FacadeServiceImplService() {
        super( WSDL_LOCATION, SERVICE );
    }


    /** @return returns FacadeService */
    @WebEndpoint( name = "FacadeServiceImplPort" )
    public FacadeService getFacadeServiceImplPort() {
        return super.getPort( FacadeServiceImplPort, FacadeService.class );
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will
     *                 have their default values.
     *
     * @return returns FacadeService
     */
    @WebEndpoint( name = "FacadeServiceImplPort" )
    public FacadeService getFacadeServiceImplPort( WebServiceFeature... features ) {
        return super.getPort( FacadeServiceImplPort, FacadeService.class, features );
    }

}
