package cz.cvut.fel.aos.service.facade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebService( targetNamespace = "http://facade.service.aos.fel.cvut.cz/", name = "FacadeService" )
@XmlSeeAlso( { ObjectFactory.class } )
public interface FacadeService {

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "cancelReservation", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.CancelReservation" )
    @WebMethod
    @ResponseWrapper( localName = "cancelReservationResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.CancelReservationResponse" )
    public javax.activation.DataHandler cancelReservation(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password
    ) throws NoSuchReservationException, SecurityException;

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findFlightsTo", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlightsTo" )
    @WebMethod
    @ResponseWrapper( localName = "findFlightsToResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlightsToResponse" )
    public java.util.List<cz.cvut.fel.aos.service.facade.Flight> findFlightsTo(
            @WebParam( name = "intervalFrom", targetNamespace = "" )
            java.util.Date intervalFrom,
            @WebParam( name = "intervalTo", targetNamespace = "" )
            java.util.Date intervalTo,
            @WebParam( name = "codeTo", targetNamespace = "" )
            java.lang.String codeTo
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findFlightsFrom", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlightsFrom" )
    @WebMethod
    @ResponseWrapper( localName = "findFlightsFromResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlightsFromResponse" )
    public java.util.List<cz.cvut.fel.aos.service.facade.Flight> findFlightsFrom(
            @WebParam( name = "intervalFrom", targetNamespace = "" )
            java.util.Date intervalFrom,
            @WebParam( name = "intervalTo", targetNamespace = "" )
            java.util.Date intervalTo,
            @WebParam( name = "codeFrom", targetNamespace = "" )
            java.lang.String codeFrom
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "payFromCanceledReservation", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PayFromCanceledReservation" )
    @WebMethod
    @ResponseWrapper( localName = "payFromCanceledReservationResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PayFromCanceledReservationResponse" )
    public boolean payFromCanceledReservation(
            @WebParam( name = "reservationIdFrom", targetNamespace = "" )
            long reservationIdFrom,
            @WebParam( name = "passwordFrom", targetNamespace = "" )
            java.lang.String passwordFrom,
            @WebParam( name = "reservationIdTo", targetNamespace = "" )
            long reservationIdTo,
            @WebParam( name = "passwordTo", targetNamespace = "" )
            java.lang.String passwordTo
    ) throws NoSuchReservationException, SecurityException, InvalidPaymentException;

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "printTicket", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PrintTicket" )
    @WebMethod
    @ResponseWrapper( localName = "printTicketResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PrintTicketResponse" )
    public javax.activation.DataHandler printTicket(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password
    ) throws NoSuchReservationException, SecurityException, ReservationNotPaidException;

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findFlights", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlights" )
    @WebMethod
    @ResponseWrapper( localName = "findFlightsResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindFlightsResponse" )
    public java.util.List<cz.cvut.fel.aos.service.facade.Flight> findFlights(
            @WebParam( name = "intervalFrom", targetNamespace = "" )
            java.util.Date intervalFrom,
            @WebParam( name = "intervalTo", targetNamespace = "" )
            java.util.Date intervalTo,
            @WebParam( name = "codeFrom", targetNamespace = "" )
            java.lang.String codeFrom,
            @WebParam( name = "codeTo", targetNamespace = "" )
            java.lang.String codeTo
    );

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "createReservation", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.CreateReservation" )
    @WebMethod
    @ResponseWrapper( localName = "createReservationResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.CreateReservationResponse" )
    public cz.cvut.fel.aos.service.facade.SuccessfulReservation createReservation(
            @WebParam( name = "flightNumber", targetNamespace = "" )
            java.lang.String flightNumber,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password,
            @WebParam( name = "count", targetNamespace = "" )
            int count
    ) throws FullFlightException;

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findAllDestinations", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindAllDestinations" )
    @WebMethod
    @ResponseWrapper( localName = "findAllDestinationsResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindAllDestinationsResponse" )
    public java.util.List<cz.cvut.fel.aos.service.facade.Destination> findAllDestinations();

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "payVisa", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PayVisa" )
    @WebMethod
    @ResponseWrapper( localName = "payVisaResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.PayVisaResponse" )
    public javax.activation.DataHandler payVisa(
            @WebParam( name = "reservationId", targetNamespace = "" )
            long reservationId,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password,
            @WebParam( name = "cardName", targetNamespace = "" )
            java.lang.String cardName,
            @WebParam( name = "creditCard", targetNamespace = "" )
            long creditCard,
            @WebParam( name = "validUntil", targetNamespace = "" )
            java.util.Date validUntil,
            @WebParam( name = "verificationCode", targetNamespace = "" )
            int verificationCode
    ) throws NoSuchReservationException, SecurityException, InvalidPaymentException;

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findReservation", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindReservation" )
    @WebMethod
    @ResponseWrapper( localName = "findReservationResponse", targetNamespace = "http://facade.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.facade.FindReservationResponse" )
    public cz.cvut.fel.aos.service.facade.Reservation findReservation(
            @WebParam( name = "reservation", targetNamespace = "" )
            long reservation,
            @WebParam( name = "password", targetNamespace = "" )
            java.lang.String password
    ) throws SecurityException;
}
