package cz.cvut.fel.aos.service.facade;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "FullFlightFault", targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class FullFlightException extends Exception {

    public static final long serialVersionUID = 20121104152907L;

    private cz.cvut.fel.aos.service.facade.FullFlightFault fullFlightFault;

    public FullFlightException() {
        super();
    }

    public FullFlightException( String message ) {
        super( message );
    }

    public FullFlightException( String message, Throwable cause ) {
        super( message, cause );
    }

    public FullFlightException( String message, cz.cvut.fel.aos.service.facade.FullFlightFault fullFlightFault ) {
        super( message );
        this.fullFlightFault = fullFlightFault;
    }

    public FullFlightException( String message, cz.cvut.fel.aos.service.facade.FullFlightFault fullFlightFault, Throwable cause ) {
        super( message, cause );
        this.fullFlightFault = fullFlightFault;
    }

    public cz.cvut.fel.aos.service.facade.FullFlightFault getFaultInfo() {
        return this.fullFlightFault;
    }
}
