package cz.cvut.fel.aos.service.facade;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "InvalidPaymentFault", targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class InvalidPaymentException extends Exception {

    public static final long serialVersionUID = 20121104152907L;

    private cz.cvut.fel.aos.service.facade.InvalidPaymentFault invalidPaymentFault;

    public InvalidPaymentException() {
        super();
    }

    public InvalidPaymentException( String message ) {
        super( message );
    }

    public InvalidPaymentException( String message, Throwable cause ) {
        super( message, cause );
    }

    public InvalidPaymentException( String message, cz.cvut.fel.aos.service.facade.InvalidPaymentFault invalidPaymentFault ) {
        super( message );
        this.invalidPaymentFault = invalidPaymentFault;
    }

    public InvalidPaymentException( String message, cz.cvut.fel.aos.service.facade.InvalidPaymentFault invalidPaymentFault, Throwable cause ) {
        super( message, cause );
        this.invalidPaymentFault = invalidPaymentFault;
    }

    public cz.cvut.fel.aos.service.facade.InvalidPaymentFault getFaultInfo() {
        return this.invalidPaymentFault;
    }
}
