package cz.cvut.fel.aos.service.facade;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "NoSuchReservationFault", targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class NoSuchReservationException extends Exception {

    public static final long serialVersionUID = 20121104152907L;

    private cz.cvut.fel.aos.service.facade.NoSuchReservationFault noSuchReservationFault;

    public NoSuchReservationException() {
        super();
    }

    public NoSuchReservationException( String message ) {
        super( message );
    }

    public NoSuchReservationException( String message, Throwable cause ) {
        super( message, cause );
    }

    public NoSuchReservationException( String message, cz.cvut.fel.aos.service.facade.NoSuchReservationFault noSuchReservationFault ) {
        super( message );
        this.noSuchReservationFault = noSuchReservationFault;
    }

    public NoSuchReservationException( String message, cz.cvut.fel.aos.service.facade.NoSuchReservationFault noSuchReservationFault, Throwable cause ) {
        super( message, cause );
        this.noSuchReservationFault = noSuchReservationFault;
    }

    public cz.cvut.fel.aos.service.facade.NoSuchReservationFault getFaultInfo() {
        return this.noSuchReservationFault;
    }
}
