package cz.cvut.fel.aos.service.facade;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "ReservationNotPaidFault", targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class ReservationNotPaidException extends Exception {

    public static final long serialVersionUID = 20121104152907L;

    private cz.cvut.fel.aos.service.facade.ReservationNotPaidFault reservationNotPaidFault;

    public ReservationNotPaidException() {
        super();
    }

    public ReservationNotPaidException( String message ) {
        super( message );
    }

    public ReservationNotPaidException( String message, Throwable cause ) {
        super( message, cause );
    }

    public ReservationNotPaidException( String message, cz.cvut.fel.aos.service.facade.ReservationNotPaidFault reservationNotPaidFault ) {
        super( message );
        this.reservationNotPaidFault = reservationNotPaidFault;
    }

    public ReservationNotPaidException( String message, cz.cvut.fel.aos.service.facade.ReservationNotPaidFault reservationNotPaidFault, Throwable cause ) {
        super( message, cause );
        this.reservationNotPaidFault = reservationNotPaidFault;
    }

    public cz.cvut.fel.aos.service.facade.ReservationNotPaidFault getFaultInfo() {
        return this.reservationNotPaidFault;
    }
}
