package cz.cvut.fel.aos.service.facade;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 15:29:07 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "SecurityFault", targetNamespace = "http://facade.service.aos.fel.cvut.cz/" )
public class SecurityException extends Exception {

    public static final long serialVersionUID = 20121104152907L;

    private cz.cvut.fel.aos.service.facade.SecurityFault securityFault;

    public SecurityException() {
        super();
    }

    public SecurityException( String message ) {
        super( message );
    }

    public SecurityException( String message, Throwable cause ) {
        super( message, cause );
    }

    public SecurityException( String message, cz.cvut.fel.aos.service.facade.SecurityFault securityFault ) {
        super( message );
        this.securityFault = securityFault;
    }

    public SecurityException( String message, cz.cvut.fel.aos.service.facade.SecurityFault securityFault, Throwable cause ) {
        super( message, cause );
        this.securityFault = securityFault;
    }

    public cz.cvut.fel.aos.service.facade.SecurityFault getFaultInfo() {
        return this.securityFault;
    }
}
