package cz.cvut.fel.aos.booking.service.destination;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;

/** This class was generated by Apache CXF 2.3.1 Mon Oct 22 20:14:49 CEST 2012 Generated source version: 2.3.1 */
@XmlSeeAlso( { ObjectFactory.class } )
@WebService( targetNamespace = "http://destination.service.booking.aos.fel.cvut.cz/", name = "DestinationService" )
public interface DestinationService {

    @WebMethod
    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findAll", targetNamespace = "http://destination.service.booking.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.booking.service.destination.FindAll" )
    @ResponseWrapper( localName = "findAllResponse", targetNamespace = "http://destination.service.booking.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.booking.service.destination.FindAllResponse" )
    List<Destination> findAll();
}
