package cz.cvut.fel.aos.service.payment;

import javax.xml.ws.WebFault;


/** This class was generated by Apache CXF 2.3.1 Sat Nov 03 16:20:34 CET 2012 Generated source version: 2.3.1 */

@WebFault( name = "SecurityFault", targetNamespace = "http://payment.service.aos.fel.cvut.cz/" )
public class SecurityException extends Exception {

    public static final long serialVersionUID = 20121103162034L;

    private cz.cvut.fel.aos.service.payment.SecurityFault securityFault;

    public SecurityException() {
        super();
    }

    public SecurityException( String message ) {
        super( message );
    }

    public SecurityException( String message, Throwable cause ) {
        super( message, cause );
    }

    public SecurityException( String message, cz.cvut.fel.aos.service.payment.SecurityFault securityFault ) {
        super( message );
        this.securityFault = securityFault;
    }

    public SecurityException( String message, cz.cvut.fel.aos.service.payment.SecurityFault securityFault, Throwable cause ) {
        super( message, cause );
        this.securityFault = securityFault;
    }

    public cz.cvut.fel.aos.service.payment.SecurityFault getFaultInfo() {
        return this.securityFault;
    }
}
