package cz.cvut.fel.aos.service.destination;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by Apache CXF 2.3.1 Sun Nov 04 12:34:38 CET 2012 Generated source version: 2.3.1 */

@WebService( targetNamespace = "http://destination.service.aos.fel.cvut.cz/", name = "DestinationService" )
@XmlSeeAlso( { ObjectFactory.class } )
public interface DestinationService {

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findAllDestinations", targetNamespace = "http://destination.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.destination.FindAllDestinations" )
    @WebMethod
    @ResponseWrapper( localName = "findAllDestinationsResponse", targetNamespace = "http://destination.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.destination.FindAllDestinationsResponse" )
    public java.util.List<cz.cvut.fel.aos.service.destination.Destination> findAllDestinations();
}
