package cz.cvut.fel.aos.service.destination;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by Apache CXF 2.3.1 Sat Nov 03 16:20:02 CET 2012 Generated source version: 2.3.1 */

@WebService( targetNamespace = "http://destination.service.aos.fel.cvut.cz/", name = "DestinationService" )
@XmlSeeAlso( { ObjectFactory.class } )
public interface DestinationService {

    @WebResult( name = "return", targetNamespace = "" )
    @RequestWrapper( localName = "findAll", targetNamespace = "http://destination.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.destination.FindAll" )
    @WebMethod
    @ResponseWrapper( localName = "findAllResponse", targetNamespace = "http://destination.service.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.service.destination.FindAllResponse" )
    public java.util.List<cz.cvut.fel.aos.service.destination.Destination> findAll();
}
